name: Regular Exam Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_run_unit_tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm install
    - name: Run the Unit tests
      run: npm run test:unit
    - name: Print user's Username
      run: echo "slamster7"

  build_and_run_ui_tests:
    needs: build_and_run_unit_tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui

  deploy:
    needs: build_and_run_ui_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the application to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SLAMSTER_APP_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.SLAMSTER_APPLICATION_API_KEY }}
    

